spring:
  application:
    name: task-service
  datasource:
    url: jdbc:mysql://localhost:3306/tasks
    username: root
    password: 
    
  jpa:
    generate-ddl: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

server:
  port: 8083
  
  
